config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks =>  "callbacks"}
  post '/auth/:provider/callback' => 'authentications#create'
  root to: 'pages#home'

  get 'components' => 'pages#components'
  get 'loadingpage' => 'backgrounds#loadingpage', as: :loadingpage
  get 'shouldwego' => 'backgrounds#shouldwego', as: :shouldwego
  post 'twitter_delete' => 'contents#twitter_delete', as: :twitter_delete

  resources :preferences, only: [:index, :update, :destroy]
  resources :topics, only: [:new, :create, :update, :destroy, :edit]
  resources :keywords, only: [:new, :create, :update, :destroy]
  resources :contents, only: [ :index, :update]
  resources :userstatistics, only: [ :index, :show]
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'

  # end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :content_keywords, dependent: :destroy
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    skip_after_action :verify_authorized, only: [:twitter_delete]

  def index
    conditions = {scan_date: Date.today}
    conditions[:external_provider] = params[:external_provider] if params[:external_provider].present?
    conditions[:file_type] = params[:file_type] if params[:file_type].present?

    @contents = policy_scope(Content.where(conditions).order(coef_total: :desc))
    @contents_file_type =["image", "post", "like"]

    if params[:external_provider]
      @contents_provider = [params[:external_provider]]
    elsif current_user.facebook.nil?
      @contents_provider =["twitter"]
    elsif current_user.twitter.nil?
      @contents_provider = ["facebook"]
    else
      @contents_provider =["facebook", "twitter"]
    end

    @selection = policy_scope(Content.where(selected: true, scan_date: Date.today))
  end

  def update
    @content = Content.find(params[:id])
    authorize @content
    if @content.update(selected: params_detail[:selected] == "0")
      @compteur = Content.where(selected: true).size
      respond_to do |format|
        format.js
      end
    else
    end
  end


  def spot(provider, file_type, number = nil)
    if number == nil
      @contents = policy_scope(Content)
                  .where(external_provider: provider, file_type: file_type)
                  .order(coef_total: :desc)
    else
      @contents = policy_scope(Content)
                    .where(external_provider: provider, file_type: file_type)
                    .order(coef_total: :desc)
                    .limit(number.to_i)
    end
  end

  def twitter_delete
    TwitterDelete.new(current_user).delete
    redirect_to '/contents?selected=true'
  end

  private

  def params_detail
    params.require(:content).permit(:selected)
  end
end

app/views/contents/index.html.erb
<%= render 'shared/filterbar'%>
<div class="offset_filterbar">
  <div class=" prime-container">
    <% unless params[:selected] || params[:file_type] || params[:external_provider] %>
      <div class="explanation snexplanation">
          <h4> Sensitive contents are highlighted with  <img class="tiny-icon" src="/assets/warning-e7d5c8dccc71b98b5057f9970a212f96547b2b7cebd56c3602af8d81496ecda3.svg"> </h4>
          <div class="select-text">
            <h4> Select the elements you want to get rid of with  </h4>
          <div id="center-select-example"> <img class="select-example" src="https://res.cloudinary.com/wmat/image/upload/v1541771097/select_example.jpg"></div>
          </div>
          <div class="arrow-elements"><h4> Once you've made your choice click on "Make my elements private" up here</h4><i class="far fa-arrow-alt-circle-up bluearrow"></i></div>
        </ul>
      </div>
    <% end %>
        <!-- trier d'abord par provider  trier par media  -->
    <div class="container" id="container-cards" >
      <% unless @contents.nil? %>
        <% if params[:selected]%>
          <% unless @selection.where(external_provider: "facebook").empty? %>
            <div class="text-center">
              <h2>Facebook Content</h2>
              <div class="row">
                <div class="sn-explanation">
                  <div class="text-sn">
                    <h4>Click on your posts and images and change the privacy settings to private</h4>
                    <h4>Unlike your sensitive likes</h4>
                  </div>
                </div>
              </div>
              <div class="row">
                <% @selection.where(external_provider: "facebook").each do |publication| %>
                  <%= render 'shared/selectionlink', publication: publication %>
                <% end %>
              </div>
            </div>
          <% end %>
          <% if !@selection.where(external_provider: "facebook").empty? && !@selection.where(external_provider: "twitter").empty? %>
            <div class="line"></div>
          <% end %>
          <% unless @selection.where(external_provider: "twitter").empty? %>
            <div class="text-center">
              <h2>Twitter Content</h2>
              <div class="row">
                <div class="sn-explanation">
                  <div class="text-sn">
                    <h4>Clink on the button at the bottom to delete your tweets</h4>
                    <h4>as well as your twitter subscriptions</h4>
                  </div>
                </div>
              </div>
              <div class="row">
                <% @selection.where(external_provider: "twitter").each do |publication| %>
                  <%= render 'shared/selectionlink', publication: publication %>
                <% end %>
              </div>
              <br>
              <%= link_to "Delete elements", twitter_delete_path, method: :post, class: "blue-submit-btn" %>
            </div>
          <% end %>
        <% elsif params[:file_type] %>
          <% @contents_provider.each do |external_prov| %>
            <h2 class="category"> <%= external_prov.capitalize %> <%=params[:file_type].capitalize %>s </h2>
              <% if @contents.where(file_type: params[:file_type], external_provider: external_prov).empty? %>
                <h3>You don't have any public content</h3>
              <% else %>
              <div class="row">
                <%@contents.where(file_type: params[:file_type], external_provider: external_prov).each do |publication| %>
                  <% unless publication.nil? %>
                    <%= render 'shared/card', publication: publication %>
                  <% end %>
                <% end %>
              </div>
              <% end %>
          <% end %>
        <% else %>
          <% @contents_provider.each do |external_prov| %>
            <%@contents_file_type.each do |type| %>
               <h2 class="category"> <%= external_prov.capitalize %>
                 <% if external_prov == "twitter" && type == "like" %>
                    Subscriptions
                 <% else %>
                   <%= type.capitalize %>s
                 <% end %>
               </h2>
               <% if @contents.where(file_type: type, external_provider: external_prov).empty?  %>
                 <h3> You don't have any public content </h3>
               <% else %>
                 <div class="row">
                    <%@contents.where(file_type: type, external_provider: external_prov).limit(5).each do |publication| %>
                      <%= render 'shared/card', publication: publication %>
                    <% end %>
                    <%= render 'shared/cardlink', publication: @contents.where(file_type: type, external_provider: external_prov).limit(6).last, external_prov: external_prov %>
                 </div>
               <%end%>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <div class="text-center"> <h2> You don"t have any public content! Congrats 🎉 </h2> </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/update.js.erb
function updateCompteur() {
  const span = document.getElementById("compteur");
  span.innerText = "<%= @compteur %>";
}

updateCompteur()