config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks =>  "callbacks"}
  post '/auth/:provider/callback' => 'authentications#create'
  root to: 'pages#home'

  get 'components' => 'pages#components'
  get 'loadingpage' => 'backgrounds#loadingpage', as: :loadingpage
  get 'shouldwego' => 'backgrounds#shouldwego', as: :shouldwego
  post 'twitter_delete' => 'contents#twitter_delete', as: :twitter_delete

  resources :preferences, only: [:index, :update, :destroy]
  resources :topics, only: [:new, :create, :update, :destroy, :edit]
  resources :keywords, only: [:new, :create, :update, :destroy]
  resources :contents, only: [ :index, :update]
  resources :userstatistics, only: [ :index, :show]
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'

  # end
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  skip_after_action :verify_authorized, only: [:loadingpage, :shouldwego]

  def loadingpage

    if Content.where(user: current_user, scan_date: Date.today).empty?
      FacebookJob.perform_later(current_user.id)
    end
  end

  def checker

  end

  def shouldwego
    length = 6 + Topic.where(user: current_user).length
    if Userstatistic.find_by(user: current_user, date: Date.today).nil?
      a = nil
    elsif Userstatistic.find_by(user: current_user, date: Date.today).topicstatistics.length == length
      a = Userstatistic.find_by(user: current_user, date: Date.today).id
    else
      a = nil
    end
    render json: a.to_json
  end

end



  # def loadingpage
  #   render 'backgrounds/loadingpage',layout: 'application'
  #   PreferenceInitializer.new(current_user).create_pref if Preference.where(user: current_user).empty?
  #   if Content.where(user: current_user, scan_date: Date.today).empty?
  #     FacebookJob.perform_later(current_user.id)
  #   end
  #   BackgroundFinished.new(current_user).shouldwego
  #   redirect_to userstatistic_path(Userstatistic.find_by(date: Date.today, user: current_user))
  # end

app/views/backgrounds/loadingpage.html.erb
<div class="fade-in">
  <div class="loading-page">
      <h1 class="loading-message">Please wait while we load and analyze your content<span>.</span><span>.</span><span>.</span></h1>
    <div class="Loader"></div>
  <!--   <%= link_to "Loading is finished", userstatistics_path, class: "btn-white-and-blue" %> -->
  </div>
</div>


<% content_for :javascript do %>
  <script>
    setInterval(function (){
      $.get('<%= shouldwego_path %>', function(data) {
        console.log(data);
        if (data) {
          window.location = '/userstatistics/' + data
        }
      })
    }, 3000)
  </script>
<% end %>