config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks =>  "callbacks"}
  post '/auth/:provider/callback' => 'authentications#create'
  root to: 'pages#home'

  get 'components' => 'pages#components'
  get 'loadingpage' => 'backgrounds#loadingpage', as: :loadingpage
  get 'shouldwego' => 'backgrounds#shouldwego', as: :shouldwego
  post 'twitter_delete' => 'contents#twitter_delete', as: :twitter_delete

  resources :preferences, only: [:index, :update, :destroy]
  resources :topics, only: [:new, :create, :update, :destroy, :edit]
  resources :keywords, only: [:new, :create, :update, :destroy]
  resources :contents, only: [ :index, :update]
  resources :userstatistics, only: [ :index, :show]
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'

  # end
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Prime Privacy</h1>
    <div id="banner-logo">
      <img class="banner-logo"src=<%= image_path "logo.png" %> alt="logo">
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="card">
        <% if publication.nil? %>
          Missing content
        <% else %>
          <%= form_for publication, remote: true do |f| %>
            <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
            <%= f.check_box :selected, id: "selection-#{publication.id}" %>
            <label for="selection-<%= publication.id %>">Select</label>
          <% end %>
          <% if publication.file_type == "image" %>
            <div class="image" style="background-image: url(<%=publication.url_image%>);" ></div>
          <% else %>
            <div class="post">
              <% if publication.external_provider == "twitter" && publication.file_type == "like" %>
                <h2 class="<%=publication.external_provider%>"> Subscription </h2>
              <% else %>
                <h2 class="<%=publication.external_provider%>""><%=publication.file_type.capitalize %></h2>
              <% end %>
              <div class="<%=publication.file_type%>-content">
              <% if publication.file_type == "like" && publication.external_provider == "twitter" %>
                <i class="fab fa-twitter"></i>
              <%else%>
                <i class="far fa-thumbs-up"></i>
              <%end%>
                <p><%= publication.text_publication %></p>
              </div>
            </div>
          <% end %>
        <% end %>

        <% if publication.coef_total > 0 %>
        <%=image_tag "warning.svg", class:"sensitive-card" %>
        <%end%>

        <% if publication.external_provider == "twitter" && publication.deleted == true %>
          <div class="card-link link-post2"></div>
          <div class="card-description ">
            <h2 > Deleted </h2>
          </div>
        <% else %>
        <% end %>
      </div>
    </div>

app/views/shared/_cardlink.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <div class="card">
    <% unless publication.nil? %>
      <% if publication.file_type == "image" %>
        <div class="image" style="background: url(<%=publication.url_image%>);" >
          <%= link_to '',"?external_provider=#{external_prov}&file_type=#{publication.file_type}", class:"card-link link-post"%>
          <div class="card-description">
            <h2>See All</h2>
          </div>
        </div>
      <% else %>
        <div class="post">
          <%= link_to '',"?external_provider=#{external_prov}&file_type=#{publication.file_type}", class:"card-link link-post"%>
          <% if publication.external_provider == "twitter" && publication.file_type == "like" %>
            <h2 class="<%=publication.external_provider%>"> Subscription </h2>
          <% else %>
            <h2 class="<%=publication.external_provider%>""><%=publication.file_type.capitalize %></h2>
          <% end %>
          <div class="<%=publication.file_type%>-content">
            <% if publication.file_type == "like" && publication.external_provider == "twitter" %>
              <i class="fab fa-twitter"></i>
            <%else%>
              <i class="far fa-thumbs-up"></i>
            <%end%>
            <p><%= publication.text_publication %></p>
          </div>
        </div>
      <%end%>
      <div class="card-description">
        <h2>See All</h2>
      </div>
    <% else %>
    <% end %>
  </div>
</div>

app/views/shared/_draglist.erb
<div class="draglist-container bg-black">
  <ul class="sortable topic-list list-unstyled" id="draglist">
    <% @preferences.each_with_sortable_id do |preference, sortable_id| %>
      <li class="draglist-box" id="<%= sortable_id %>">
        <% if preference.topic %>
        <%= image_tag preference.topic.picto, class: 'picto' %>
        <p class="topic-name"><%= preference.topic.name %></p>
        <% unless preference.topic.user != current_user %>
          <%= link_to '', edit_topic_path(preference.topic), remote: true, :class => "far fa-edit edit-picto" %>
        <% end %>
        <%= link_to '', preference, method: :delete, remote: true, :class => "far fa-times-circle delete-cross" %>
        <% end %>
        <i class="fas fa-arrows-alt-v drag"></i>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_fbstats.html.erb
<h4>Your Facebook public content over time</h4>
<%= area_chart [
  {name: "Facebook public content SENSITIVE", data: @userstatistics.group_by_month(:date, series:false).sum(:total_fb_public_sensitive)},
  {name: "Facebook public content", data: @userstatistics.group_by_month(:date, series:false).sum(:total_fb_public)}
], colors: ["#E7746F", "#3B5998"], legend: "bottom"  %>

app/views/shared/_filterbar.erb
<div class="filterbar-prime navbar-fixed-top">
  <ul class="nav nav-tabs prime-tabs">
    <li role="presentation">
      <div class="prime-tab" id="backtocontent">
          <%= link_to '⇦ Back to All Content', contents_path, class:"linkto back-to-content-btn" %>
      </div>
    </li>

    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle prime-tab" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <div class="prime-tab">
          <%= params[:external_provider] ? params[:external_provider].capitalize : "Social Media" %> <span class="caret"></span>
        </div>
      </a>
      <ul class="dropdown-menu filterbar-prime-dropdown-menu">
          <li><%= link_to 'Facebook',"?external_provider=facebook", class:"linkto dropdown-item"%></li>
          <li><%= link_to 'Twitter',"?external_provider=twitter", class:"linkto dropdown-item"%></li>
          <div class="dropdown-divider"></div>
          <li><%= link_to 'Add another account', userstatistics_path, class:"linkto dropdown-item"%></li>
      </ul>
    </li>

    <li>
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <div class="prime-tab">
          <%= params[:file_type] ? params[:file_type].capitalize + "s" : "Category" %><span class="caret"></span>
        </div>
      </a>
      <ul class="dropdown-menu filterbar-prime-dropdown-menu">
        <li class="dropdown-item"><%= link_to 'Images', params[:external_provider] ? "?external_provider=#{params[:external_provider]}&file_type=image" : "?file_type=image" , class:"linkto dropdown-item"%></li>
        <li class="dropdown-item"><%= link_to 'Posts', params[:external_provider] ? "?external_provider=#{params[:external_provider]}&file_type=post" : "?file_type=post" , class:"linkto dropdown-item"%></li>
        <li class="dropdown-item" href="#"><%= link_to 'Likes / Subscriptions', params[:external_provider] ? "?external_provider=#{params[:external_provider]}&file_type=like" : "?file_type=like" , class:"linkto dropdown-item"%></li>
      </ul>
    </li>


    <li> <%= link_to "?selected=true",id:"filterbar-button", class:"checkout-button prime-tab" do %>
      Make your <span id="compteur"> <%= @selection.size %></span> elements private
      <% end %>

    </li>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_inputbox.html.erb
<div class="topics-container add-new-topics bg-black">
  <form action="/topics" class="topic-form" method="POST">
    <h1 class="topic-header center">Add a sensitivity topic</h1>
    <div id="mainform-topic">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input id="topic-name" name="topic[name]" class="input-box topic-input" type="text" placeholder="Topic name">
      <input id="add-topic-btn" class="submit-btn-topic" type="submit" value="Add">
    </div>

    <div id="subform-topic" hidden>
      <h2 id="topic-name-reminder" class="text-center"></h2>
      <h4 id="keyword-explanation" class="topiclist-explained text-center"></h4>
      <div id="words-wrapper">
        <input name="keyword[]" class="input-box word-input" type="text" placeholder="New word" >
      </div>
      <div id="words-form-btns">
        <input id="add-another-word" type="submit" value="⨁ Add another word">
        <div id="btn-submission-topic">
          <input id="cancel-btn" type="button" class="submit-btn-topic" value="Cancel" onClick="window.location.reload()">
          <input id="confirm-topic-btn" class="submit-btn-topic" type="submit" value="Confirm addition">
        </div>
      </div>
    </div>
  </form>
</div>

app/views/shared/_loading.html.erb
<div class="loading-page">
  <% if !Content.where(user: current_user, scan_date: Date.today).empty? %>
    <h1 class="loading-message">Loading your session<span>.</span><span>.</span><span>.</span></h1>
    <% stat = Userstatistic.find_by(user: current_user, date: Date.today) %>
    <%= link_to "Loading is finished", userstatistic_path(stat), class: "btn-white-and-blue" %>
  <% else %>
    <h1 class="loading-message">Importing your little secrets<span>.</span><span>.</span><span>.</span></h1>
    <% wait = true %>
    <% length = 6 + Topic.where(user: current_user).length %>
    <% while wait %>
      <% stat = Userstatistic.find_by(user: current_user, date: Date.today) %>
      <% sleep(5) %>
      <% if !stat.nil?%>
        <% wait = false if stat.topicstatistics.length == length %>
      <% end %>
    <% end %>
    <%= link_to "Loading is finished", userstatistic_path(stat), class: "btn-white-and-blue" %>
  <% end %>
  <div class="Loader"></div>
<!--   <%= link_to "Loading is finished", userstatistics_path, class: "btn-white-and-blue" %> -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-prime navbar-fixed-top">
  <!-- Left Navigation -->
  <div class="navbar-prime-left hidden-xs">
    <% if current_user.nil? %>
      <%= link_to "Prime Privacy", "/", class: "navbar-prime-title" %>
    <% else %>
      <%= link_to "Prime Privacy", userstatistics_path, class: "navbar-prime-title" %>
    <% end %>
  </div>

  <!-- Logo -->
  <% if current_user.nil? %>
    <%= link_to root_path, class: "navbar-prime-logo page-top page-center" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% else %>
    <%= link_to userstatistics_path, class: "navbar-prime-logo page-top page-center" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-prime-right">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-prime-item">
        <div class="dropdown">
          <% if !current_user.facebook.nil?%>
            <% if !current_user.facebook.photo.nil? %>
              <%= image_tag current_user.facebook.photo, class: "avatar dropdown-toggle", id: "navbar-prime-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "https://cdn0.iconfinder.com/data/icons/user-pictures/100/matureman1-512.png", class: "avatar dropdown-toggle", id: "navbar-prime-menu", "data-toggle" => "dropdown" %>
            <% end %>
          <% else %>
          <%= image_tag "https://cdn0.iconfinder.com/data/icons/user-pictures/100/matureman1-512.png", class: "avatar dropdown-toggle", id: "navbar-prime-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-prime-dropdown-menu">
            <li>
              <%= link_to userstatistics_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Edit account") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-prime-item navbar-prime-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_page_offset.erb
<div class="page-offset-navbar"></div>

app/views/shared/_selectionlink.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">

    <% unless publication.nil? %>
      <div class="card">
        <% if publication.file_type == "image" %>
          <div class="image" style="background: url(<%=publication.url_image%>);" >
            <% unless publication.external_provider == "twitter"  %>
              <a href="<%=publication.publication_url%>" target="_blank" class="card-link link-post2"></a>
              <div class="card-description">
                <h2>Go to post</h2>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="post">
             <div class="card-link"></div>

            <% if publication.external_provider == "twitter" && publication.file_type == "like" %>
              <h2 class="<%=publication.external_provider%>"> Subscription </h2>
            <% else %>
              <% unless publication.external_provider == "twitter"%>
                 <a href="<%=publication.publication_url%>" target="_blank" class="card-link link-post2"></a>
              <% end %>
              <h2 class="<%=publication.external_provider%>""><%=publication.file_type.capitalize %></h2>
            <% end %>
            <div class="<%=publication.file_type%>-content">
              <% if publication.file_type == "like" && publication.external_provider == "twitter" %>
                <i class="fab fa-twitter"></i>
              <%else%>
                <i class="far fa-thumbs-up"></i>
              <%end%>
              <p><%= publication.text_publication %></p>
            </div>
          </div>
        <%end%>
        <% if publication.external_provider == "twitter" && publication.deleted == true %>
          <div class="card-link link-post2"></div>
          <div class="card-description ">
            <h2 > Deleted </h2>
          </div>
        <% elsif publication.external_provider == "twitter" %>

        <% else %>
          <div class="card-description">
            <h2>Go to post</h2>
          </div>
        <% end %>
      </div>
    <% end %>
</div>

app/views/shared/_topicstat.html.erb
<% hash = {} %>
<% topicstat = Topicstatistic.where(userstatistic: @userstatistic) %>
<% topicstat.each do |topicstat| %>
<% hash[Topic.find(topicstat[:topic_id])[:name]] = topicstat[:numberofinstances] %>
<%end%>
<%= column_chart((hash.sort_by { |topic, instances| instances }).reverse, colors: ["ffcd3c"]) %>

app/views/shared/_twstats.html.erb
<h4>Your Twitter public content over time</h4>
<%= area_chart [
  {name: "Twitter public content SENSITIVE", data: @userstatistics.group_by_month(:date, series:false).sum(:total_tw_public_sensitive)},
  {name: "Twitter public content", data: @userstatistics.group_by_month(:date, series:false).sum(:total_tw_public)}
], colors: ["#E7746F", "#55ACEE"], legend: "bottom"  %>