config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks =>  "callbacks"}
  post '/auth/:provider/callback' => 'authentications#create'
  root to: 'pages#home'

  get 'components' => 'pages#components'
  get 'loadingpage' => 'backgrounds#loadingpage', as: :loadingpage
  get 'shouldwego' => 'backgrounds#shouldwego', as: :shouldwego
  post 'twitter_delete' => 'contents#twitter_delete', as: :twitter_delete

  resources :preferences, only: [:index, :update, :destroy]
  resources :topics, only: [:new, :create, :update, :destroy, :edit]
  resources :keywords, only: [:new, :create, :update, :destroy]
  resources :contents, only: [ :index, :update]
  resources :userstatistics, only: [ :index, :show]
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'

  # end
end

app/models/userstatistic.rb
class Userstatistic < ApplicationRecord
  belongs_to :user
  has_many :topicstatistics, dependent: :destroy
end

app/controllers/userstatistics_controller.rb
class UserstatisticsController < ApplicationController
  def index
    @userstatistics = policy_scope(Userstatistic)
    PreferenceInitializer.new(current_user).create_pref if Preference.where(user: current_user).empty?
  end

  def show
    @userstatistic = Userstatistic.find(params[:id])
    authorize @userstatistic
  end
end

app/views/userstatistics/index.html.erb
<div class="userstatistics-page bg-texture-faded">
  <%= render 'shared/social_network_connector' %>
  <% unless Authentication.where(user: current_user).empty? %>
    <div class="row text-center">
      <%= link_to "Hide your data", preferences_path, class: "blue-submit-btn", id: "trigger-loading"%>
    </div>
  <% end %>
  <% if !@userstatistics.empty? %>
    <div class="prime-container pc-twist">
      <div class="row">
        <div class="timestats">
          <% if !current_user.facebook.nil? && !current_user.twitter.nil? %>
            <div class="col-xs-12 col-sm-6"><%= render 'shared/fbstats' %></div>
            <div class="col-xs-12 col-sm-6"><%= render 'shared/twstats' %></div>
          <% elsif !current_user.facebook.nil? && current_user.twitter.nil? %>
            <div class="col-xs-12"><%= render 'shared/fbstats' %></div>
          <% elsif current_user.facebook.nil? && !current_user.twitter.nil? %>
            <div class="col-xs-12"><%= render 'shared/twstats' %></div>
          <%end%>
        </div>
      </div>
      <div class="row">
        <div class="past-hidings">
          <h3>Past changes:</h3>
          <% @userstatistics.each do |stat| %>
            <div class="statlign">
                <% if stat.total_tw_public == 0 %>
                  <i class="logo-soc fab fa-facebook-square"></i>
                <% elsif stat.total_fb_public == 0 %>
                  <i class="logo-soc fab fa-twitter-square"></i>
                <%else%>
                  <p class="logo-soc"><i class="fab fa-facebook-square"></i> <i class="fab fa-twitter-square"></i></p>
                <%end%>
              <div class="datelog">
                <%= stat.date.to_time.strftime('%B %e, %Y') %>
              </div>
              <p class="publicnumber hidden-xs"><%= stat.total_fb_public + stat.total_tw_public%> public elements</p>
              <p class="sensitivenumber hidden-xs"><%= stat.total_fb_public_sensitive + stat.total_tw_public_sensitive %> sensitive elements</p>
              <div class="seedashb"> <%= link_to "see details", userstatistic_path(stat), class: "blue-submit-btn"%></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/userstatistics/show.html.erb
<div class="container bg-texture-faded">
  <div class="prime-container">
    <div class="row heightbigger go-to-content-btn">
      <% if @userstatistic.date = Date.today %>
        <%= link_to "Go to your public content", contents_path, class: "blue-submit-btn text-center" %>
      <% end %>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-4 text-center">
        <%= image_tag "photo-flat.png", class: "cards-icon" %>
        <div class="datapubandsens">
          <div class="datatext text-center">
            <div class="datapublic">
              <% photos_public = @userstatistic.fb_photo_public + @userstatistic.tw_photo_public %>
              <% photos_sensitive = @userstatistic.fb_photo_public_sensitive + @userstatistic.tw_photo_public_sensitive %>
              <p class="bold"><%= photos_public %> public <%= photos_public == 1 ? "photo" : "photos" %></p>
            </div>
            <div class="amongwhich">
              <p>among which</p>
            </div>
            <div class="dataprivate">
              <p class="bold red"><%= photos_sensitive %> <%= photos_sensitive == 1 ? "is" : "are"%> sensitive</p>
            </div>
          </div>
          <div class="datagraph">
            <%= pie_chart({"non-sensitive" => photos_public - photos_sensitive, "sensitive" => photos_sensitive}, legend: false, colors: ["#F5F5F5", "#E7746F"], messages: {empty: "Congrats, no public data"}, height: "100px", width: "120px") %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= image_tag "post-flat.png", class: "cards-icon" %>
        <div class="datapubandsens">
          <div class="datatext text-center">
            <div class="datapublic">
              <% posts_public = @userstatistic.fb_post_public + @userstatistic.tw_post_public %>
              <% posts_sensitive = @userstatistic.fb_post_public_sensitive + @userstatistic.tw_post_public_sensitive %>
              <p class="bold"><%= posts_public %> public <%= posts_public == 1 ? "post" : "posts" %></p>
            </div>
            <div class="amongwhich">
              <p>among which</p>
            </div>
            <div class="dataprivate">
              <p class="bold red"><%= posts_sensitive %> <%= posts_sensitive == 1 ? "is" : "are"%> sensitive</p>
            </div>
          </div>
          <div class="datagraph">
            <%= pie_chart({"non-sensitive" => posts_public - posts_sensitive, "sensitive" => posts_sensitive}, legend: false, colors: ["#F5F5F5", "#E7746F"], messages: {empty: "Congrats, no public data"}, height: "100px", width: "120px") %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= image_tag "page-flat.png", class: "cards-icon" %>
        <div class="datapubandsens">
          <div class="datatext text-center">
            <div class="datapublic">
              <% likes_public = @userstatistic.fb_likes_public + @userstatistic.tw_likes_public %>
              <% likes_sensitive = @userstatistic.fb_likes_public_sensitive + @userstatistic.tw_likes_public_sensitive %>
              <p class="bold"><%= likes_public %> public <%= likes_public == 1 ? "subscription" : "subscriptions" %></p>
            </div>
            <div class="amongwhich">
              <p>among which</p>
            </div>
            <div class="dataprivate">
              <p class="bold red"><%= likes_sensitive %> <%= likes_sensitive == 1 ? "is" : "are"%> sensitive</p>
            </div>
          </div>
          <div class="datagraph">
            <%= pie_chart({"non sensitive" => likes_public - likes_sensitive, "sensitive" => likes_sensitive}, legend: false, colors: ["#F5F5F5", "#E7746F"], messages: {empty: "Congrats, no public data"}, height: "100px", width: "120px") %>
          </div>
        </div>
      </div>
    </div>
    <div class="line"></div>
    <% if @userstatistic.total_fb_public != 0 && @userstatistic.total_tw_public != 0 %>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <p class="text-center smallermargin">Most of your public content is on</p> <p class="bold text-center smallermargin"><%= @userstatistic.total_fb_public > @userstatistic.total_tw_public ? "Facebook" : "Twitter"%> </p>
          <div class="pie">
            <%= pie_chart({"Facebook" => @userstatistic.total_fb_public, "Twitter" => @userstatistic.total_tw_public}, legend: false, height: "170px", colors: ["#3B5998", "#55ACEE"]) %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <p class="text-center smallermargin">Most of your sensitive content is on </p> <p class=" smallermargin bold text-center"><%= @userstatistic.total_fb_public_sensitive > @userstatistic.total_tw_public_sensitive ? "Facebook" : "Twitter"%> </p>
          <div class="pie">
            <%= pie_chart({"Facebook" => @userstatistic.total_fb_public_sensitive, "Twitter" => @userstatistic.total_tw_public_sensitive}, legend: false, height: "170px", colors: ["#3B5998", "#55ACEE"]) %>
          </div>
        </div>
      </div>
      <div class="line"></div>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <h4 class="marginleft">Most common sensitive topics: </h4>
        <%= render 'shared/topicstat' %>
      </div>
    </div>
  </div>
</div>